# Generated by Django 4.2 on 2024-06-19 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='挂号预约ID', primary_key=True, serialize=False, verbose_name='挂号预约ID')),
                ('appointment_time', models.DateTimeField(blank=True, help_text='预约时间', null=True, verbose_name='预约时间')),
                ('pet_name', models.CharField(help_text='宠物名称', max_length=32, verbose_name='宠物名称')),
                ('description', models.TextField(blank=True, default='', help_text='宠物病情描述', null=True, verbose_name='宠物病情描述')),
                ('status', models.CharField(choices=[('Pending', '待确认'), ('Confirmed', '已确认'), ('Cancelled', '已取消'), ('Completed', '已完成')], default='Pending', help_text='预约状态', max_length=32, verbose_name='预约状态')),
                ('comment', models.TextField(blank=True, default='', help_text='患者评论', null=True, verbose_name='患者评论')),
            ],
            options={
                'verbose_name': '宠物预约信息',
                'verbose_name_plural': '宠物预约信息',
                'db_table': 'pet_appointment',
            },
        ),
        migrations.CreateModel(
            name='DoctorWeeklyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='医生接诊时间ID', primary_key=True, serialize=False, verbose_name='医生接诊时间ID')),
                ('day_of_week', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')], help_text='星期几', verbose_name='星期几')),
                ('start_time', models.TimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.TimeField(help_text='结束时间', verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '医生可预约时间信息',
                'verbose_name_plural': '医生可预约时间信息',
                'db_table': 'doctor_available_time',
                'ordering': ['doctor', 'day_of_week', 'start_time', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(help_text='真实姓名', max_length=32, verbose_name='真实姓名')),
                ('ID_number', models.CharField(help_text='身份证号', max_length=32, verbose_name='身份证号')),
                ('phone_number', models.CharField(help_text='手机号', max_length=32, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '患者信息',
                'verbose_name_plural': '患者信息',
                'db_table': 'patient_info',
            },
        ),
    ]
