# Generated by Django 4.2 on 2024-06-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='user',
            field=models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='doctorweeklyavailability',
            name='doctor',
            field=models.ForeignKey(help_text='医生', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_available_time', to='users.doctorinfo', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='医生', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='users.doctorinfo', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(help_text='患者', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointment.patientinfo', verbose_name='患者'),
        ),
    ]
