# Generated by Django 4.2 on 2024-06-19 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='评论ID', primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(help_text='评论内容', max_length=100000, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '帖子评论',
                'verbose_name_plural': '帖子评论',
                'db_table': 'post_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PostFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '帖子点赞信息',
                'verbose_name_plural': '帖子点赞信息',
                'db_table': 'post_favor_info',
            },
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='评论ID', primary_key=True, serialize=False, verbose_name='评论ID')),
                ('title', models.CharField(help_text='帖子标题', max_length=100, verbose_name='帖子标题')),
                ('front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='image/post', verbose_name='封面图')),
                ('brief_content', models.CharField(blank=True, default='', help_text='帖子简介', max_length=200, verbose_name='帖子简介')),
                ('content', models.TextField(help_text='帖子正文', max_length=100000, verbose_name='帖子正文')),
                ('click_num', models.PositiveIntegerField(default=0, help_text='浏览量', verbose_name='浏览量')),
                ('comment_num', models.PositiveIntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('favor_num', models.PositiveIntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '帖子信息',
                'verbose_name_plural': '帖子信息',
                'db_table': 'post_info',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, default='', help_text='标签描述', null=True, verbose_name='标签描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '帖子标签',
                'verbose_name_plural': '帖子标签',
                'db_table': 'post_tag',
            },
        ),
    ]
