# Generated by Django 4.2 on 2024-06-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='author',
            field=models.ForeignKey(help_text='发帖人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发帖人'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_posts', to='forum.posttag', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='postfavor',
            name='post',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='forum.postinfo', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='postfavor',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='post_favor', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(help_text='帖子', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='forum.postinfo', verbose_name='帖子'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(help_text='评论者', on_delete=django.db.models.deletion.CASCADE, related_name='user_post_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddConstraint(
            model_name='postfavor',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_favor_post_user'),
        ),
    ]
