# Generated by Django 4.2.13 on 2024-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinfo",
            name="front_image",
            field=models.ImageField(
                blank=True,
                help_text="封面图",
                null=True,
                upload_to="image/post/front_image",
                verbose_name="封面图",
            ),
        ),
    ]
