# Generated by Django 4.2 on 2024-06-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_initial'),
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='goodscomment',
            name='good',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='good_comment', to='goods.goodsinfo', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='goodscomment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comment', to='trades.orderinfo', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='goodscomment',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_good_comment', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
