# Generated by Django 4.2 on 2024-06-19 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='商品类别ID', primary_key=True, serialize=False, verbose_name='商品类别ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('description', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='商品ID', primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('content', models.TextField(default='', help_text='商品详情', verbose_name='商品详情')),
                ('front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='image/shop', verbose_name='封面图')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='售价', max_digits=10, verbose_name='售价')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('sold_num', models.PositiveIntegerField(default=0, help_text='销量', verbose_name='销量')),
                ('click_num', models.PositiveIntegerField(default=0, help_text='点击数', verbose_name='点击数')),
                ('comment_num', models.PositiveIntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('favor_num', models.PositiveIntegerField(default=0, help_text='赞数', verbose_name='赞数')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销')),
                ('is_ship_free', models.BooleanField(default=True, help_text='是否承担运费', verbose_name='是否承担运费')),
                ('category', models.ForeignKey(blank=True, help_text='商品类目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goods', to='goods.goodscategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='GoodsFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('good', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.goodsinfo', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品点赞信息',
                'verbose_name_plural': '商品点赞信息',
                'db_table': 'good_favor_info',
            },
        ),
    ]
