# Generated by Django 4.2 on 2024-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='certificate_image_url',
            field=models.ImageField(blank=True, help_text='职业证书照片', null=True, upload_to='image/doctors/certificate', verbose_name='职业证书照片'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='real_image_url',
            field=models.ImageField(blank=True, help_text='本人真实照片', null=True, upload_to='image/doctors/real_image', verbose_name='本人真实照片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='image/user/avatars/default_logo.png', help_text='头像', null=True, upload_to='image/user/avatars', verbose_name='头像'),
        ),
    ]
